/* 지도 마커 데이터. gamePlaces/travelPlaces 항목: coords [lat,lng], title, description, img(URL 또는 배열), country */
export const colors = ['#FF8FA8', '#8FA6FF', '#FFD580', '#A6D8A6']

export const countryColors = {
  CHINA: '#FF4D4F',
  JAPAN: '#FF9C00',
  KOREA: '#40A9FF',
  USA: '#73D13D',
  FRANCE: '#9254DE',
  GERMANY: '#FFC53D',
  TAIWAN: '#13C2C2',
}

export const gamePlaces = [
  {
    coords: [31.167719, 121.461939],
    title: '2025 Arknights: Immersive Exploration Offline Exhibition',
    country: 'CHINA',
    description: '2025 明日方舟:集成映射——沉浸式线下展',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/gamePlaces/arknightsImmersiveExplorationOfflineExhibition.jpg',
  },
  {
    coords: [37.0278618, 126.7458804],
    title: 'Attack on Titan FINAL in SEOUL Again',
    country: 'KOREA',
    description: '진격의 거인전 FINAL in Seoul',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/gamePlaces/attackonTitanFinalinSeoulAgain.jpg',
  },
  {
    coords: [31.190981, 121.304356],
    title: 'BILIBILI MACRO LINK 2024 (BML)',
    country: 'CHINA',
    description: '',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/gamePlaces/bilibiliMacroLink.jpg',
  },
  {
    coords: [31.189991, 121.302183],
    title: 'BiliBili World 2024 (BW)',
    country: 'CHINA',
    description: '',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/gamePlaces/bilibiliWorld.jpg',
  },
  {
    coords: [30.242825, 120.159751],
    title: 'Black Myth: Wukong Art Exhibition',
    country: 'CHINA',
    description: '黑神铸炼——《黑神话：悟空》艺术展',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/gamePlaces/blackMythWukongArtExhibition.JPG',
  },
  {
    coords: [30.16208, 120.205558],
    title: 'CHINA CARTOON & ANIMATION MUSEUM',
    country: 'CHINA',
    description: '杭州中国动漫博物馆',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/gamePlaces/chinaCartoonAnimationMuseum.jpg',
  },
  {
    coords: [30.161388, 120.202788],
    title: 'China International Cartoon and Animation Festival',
    country: 'CHINA',
    description: '中国国际动漫节',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/gamePlaces/chinaInternationalCartoonAndAnimationFestival.jpg',
  },
  {
    coords: [31.210205, 121.568003],
    title: 'ChinaJoy',
    country: 'CHINA',
    description: '中国国际数码互动娱乐展览会',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/gamePlaces/chinaJoy.JPG',
  },
  {
    coords: [31.235113, 121.473671],
    title: 'Digimon Adventure Exhibition Forever Young Immersive Theme Exhibition',
    country: 'CHINA',
    description: '25周年数码宝贝沉浸式主题展「永远的青春」',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/gamePlaces/digimonAdventureExhibitionForeverYoungImmersiveThemeExhibition.jpg',
  },
  {
    coords: [31.29058, 121.441854],
    title: 'EVA Statue',
    country: 'CHINA',
    description: '上海EVA初号机大雕像',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/gamePlaces/evaStatue.jpg',
  },
  {
    coords: [35.1674641, 129.1321624],
    title: 'G-STAR',
    country: 'KOREA',
    description: '국제게임전시회 지스타',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/gamePlaces/gStar.jpg',
  },
  {
    coords: [37.5549547, 126.9256065],
    title: 'Genshin Cafe in Seoul',
    country: 'KOREA',
    description: '원신 카페 인 서울',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/gamePlaces/genshinCafeinSeoul.jpg',
  },
  {
    coords: [31.189991, 121.302183],
    title: 'GENSHIN☆FES',
    country: 'CHINA',
    description: '原神☆FES in Shanghai 「跨越尘世 于此相聚」',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/gamePlaces/genshinFes.jpg',
  },
  {
    coords: [31.252278, 121.603802],
    title: 'Shanghai THE GUNDAM BASE',
    country: 'CHINA',
    description: '「THE GUNDAM BASE 高达基地(LaLaport店)」',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/gamePlaces/lalaportGundamBase.jpg',
  },
  {
    coords: [35.6998061, 139.7703584],
    title: 'MaiDreamin Akihabara',
    country: 'JAPAN',
    description: 'めいどりーみん 秋葉原 中央通り店',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/gamePlaces/maiDreaminAkihabara.png',
  },
  {
    coords: [31.167964, 121.414655],
    title: 'Neo World',
    country: 'CHINA',
    description: '[元界Neo World]元宇宙街区',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/gamePlaces/neoWorld.jpg',
  },
  {
    coords: [35.6254811, 139.7735634],
    title: 'Odaiba Gundam Base',
    country: 'JAPAN',
    description: 'ガンダムベース 東京',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/gamePlaces/odaibaGundamBase.JPG',
  },
  {
    coords: [25.0566019, 121.6181159],
    title: 'Taipei GameShow',
    country: '',
    description: '台北国际电玩展',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/gamePlaces/taipeiGameShow.JPG',
  },
  {
    coords: [35.6476899, 140.0329537],
    title: 'TOKYO GAME SHOW',
    country: 'JAPAN',
    description: '東京ゲームショウ',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/gamePlaces/tokyoGameShow.JPG',
  },
  {
    coords: [35.6244553, 139.7729168],
    title: 'Unicorn Gundam',
    country: 'JAPAN',
    description: '実物大ユニコーンガンダム立像',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/gamePlaces/unicornGundam.jpg',
  },
]

/** 여행 장소 */
export const travelPlaces = [
  {
    coords: [25.1767763, 121.4323041],
    title: 'Aletheia University',
    country: '',
    description: '真理大学',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/aletheiaUniversity.jpg',
  },
  {
    coords: [37.5866118, 126.9722361],
    title: 'ChengWaDae',
    country: 'KOREA',
    description: '청와대',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/chengWaDae.jpg',
  },
  {
    coords: [36.900395, 122.40374],
    title: 'Chishan Mingshen',
    country: 'CHINA',
    description: '石岛赤山景区-赤山明神',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/chishanMingshen.jpg',
  },
  {
    coords: [34.6685368, 135.5015172],
    title: 'Dōtonbori',
    country: 'JAPAN',
    description: '道頓堀',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/dotonbori.jpg',
  },
  {
    coords: [30.383536, 120.247243],
    title: 'Guangsha Tiandu City',
    country: 'CHINA',
    description: '广厦天都城',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/guangshaTianduCity.jpg',
  },
  {
    coords: [37.5796212, 126.9744661],
    title: 'GyeongBokGung',
    country: 'KOREA',
    description: '경복궁',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/gyeongBokGung.jpg',
  },
  {
    coords: [33.3616836, 126.5188669],
    title: 'Hallasan National Park',
    country: 'KOREA',
    description: '한라산',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/hallasanNationalPark.jpg',
  },
  {
    coords: [30.169795, 120.098741],
    title: 'Hangzhou Songcheng',
    country: 'CHINA',
    description: '杭州宋城',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/hangzhouSongcheng.JPG',
  },
  {
    coords: [45.611938, 126.241474],
    title: 'Harbin Taiping International Airport',
    country: 'CHINA',
    description: '哈尔滨太平国际机场',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/harbinTaipingInternationalAirport.jpg',
  },
  {
    coords: [37.424765, 122.115425],
    title: 'Huaxiacheng',
    country: 'CHINA',
    description: '威海华夏城旅游风景区',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/huaxiacheng.jpg',
  },
  {
    coords: [30.308018, 120.319745],
    title: 'Jinsha Lake Park',
    country: 'CHINA',
    description: '金沙湖公园',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/jinshaLakePark.jpg',
  },
  {
    coords: [35.7020229, 139.7653194],
    title: 'Kanda Myōjin',
    country: 'JAPAN',
    description: '神田明神',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/kandamyojin.jpg',
  },
  {
    coords: [30.230934, 120.148849],
    title: 'Leifeng Pagoda',
    country: 'CHINA',
    description: '雷峰塔景区',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/leifengPagoda.jpg',
  },
  {
    coords: [37.504524, 122.190069],
    title: 'Liugong Island',
    country: 'CHINA',
    description: '刘公岛景区',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/liugongIsland.jpg',
  },
  {
    coords: [32.0626, 118.7981],
    title: 'Nanjing City Wall Scenic Area',
    country: 'CHINA',
    description: '南京城墙景区',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/nanjingCityWallScenicArea.jpg',
  },
  {
    coords: [32.061456, 118.801956],
    title: 'Nanjing Confucius Temple',
    country: 'CHINA',
    description: '南京夫子庙',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/nanjingConfuciusTemple.jpg',
  },
  {
    coords: [32.058454, 118.787736],
    title: 'Nanjing Line Friends',
    country: 'CHINA',
    description: '南京 Line Friends',
    img: [
      'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/nanjingLineFriends.jpg',
      'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/nanjingLineFriends_2.JPG',
    ],
  },
  {
    coords: [41.9964804, 128.0554523],
    title: 'Paektu Mountain',
    country: 'CHINA',
    description: '백두산',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/paektuMountain.jpg',
  },
  {
    coords: [38.1195818, 128.4450015],
    title: 'Seoraksan National Park',
    country: 'KOREA',
    description: '설악산',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/seoraksanNationalPark.jpg',
  },
  {
    coords: [32.030729, 118.707481],
    title: 'Singapore-Nanjing Eco Hi-Tech Island',
    country: 'CHINA',
    description: '新加坡·南京生态科技岛科创中心',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/singapore-NanjingEcoHi-TechIsland.jpg',
  },
  {
    coords: [35.627877, 139.7692597],
    title: 'Statue of Liberty',
    country: 'JAPAN',
    description: '自由の女神像',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/statueofLiberty.JPG',
  },
  {
    coords: [25.0339808, 121.5619693],
    title: 'Taipei 101',
    country: '',
    description: '台北101大楼',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/taipei101.jpg',
  },
  {
    coords: [35.6267151, 139.882503],
    title: 'Tokyo Disney Sea',
    country: 'JAPAN',
    description: '東京ディズニーシー',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/tokyoDisneySea.jpg',
  },
  {
    coords: [35.710067, 139.8081255],
    title: 'Tokyo Skytree',
    country: 'JAPAN',
    description: '東京スカイツリー',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/tokyoSkytree.jpg',
  },
  {
    coords: [42.961627, 129.855521],
    title: 'Tumen River',
    country: 'CHINA',
    description: '图们江公园',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/tumenRiver.jpg',
  },
  {
    coords: [34.6656812, 135.4297436],
    title: 'Universal Studios Japan',
    country: 'JAPAN',
    description: 'ユニバーサル・スタジオ・ジャパン',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/universalStudiosJapan.jpg',
  },
  {
    coords: [37.531753, 122.050955],
    title: 'Weihai International Beach',
    country: 'CHINA',
    description: '威海林海湾旅游区',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/weihaiInternationalBeach.jpg',
  },
  {
    coords: [37.465201, 122.144823],
    title: 'Weihai Park',
    country: 'CHINA',
    description: '威海公园',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/weihaiPark.jpg',
  },
  {
    coords: [37.501534, 122.127901],
    title: 'XingFuMen',
    country: 'CHINA',
    description: '幸福门广场',
    img: 'https://forgamersbygamers-image.oss-cn-shanghai.aliyuncs.com/travelPlaces/xingfumen.jpg',
  },
]
